name: habit_planet
description: A new Flutter project for daily video reminders.
version: 1.0.0+4
publish_to: 'none' # Prevent accidental publishing to pub.dev

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  to_csv: 
  image_picker: 
  is_audio_playing:
  audioplayers:
  flutter_colorpicker:
  flutter_sound:
  equatable:
  bloc:
  logging:
  shared_preferences:
  swipable_stack:
  flutter_slidable:
  hydrated_bloc:
  uuid:
  flutter_bloc:
  video_player:
  camera:
  image_gallery_saver:
  intl: ^0.17.0 # For date formatting.
  sqflite: any # It's better to specify a version number for production apps.
  path_provider: ^2.1.1 # Used for finding commonly used locations on the filesystem.
  # //TODO screenshots
  grpc: ^3.2.4
  protobuf: ^3.1.0
  path: ^1.8.3
  ffmpeg_kit_flutter:
  flutter_launcher_icons: ^0.13.1
  # Add other dependencies you might need for your project.

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
dev_dependencies:  
  screenshot:
  flutter_driver:
    sdk: flutter
  test: any
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true

  # Include any assets like fonts, images, and videos.
  assets:
    - assets/audio/
    - assets/icon/
    - assets/images/

  # fonts:
  #   - family: MyCustomFont
  #     fonts:
  #       - asset: fonts/MyCustomFont-Regular.ttf
  #       - asset: fonts/MyCustomFont-Italic.ttf
  #         style: italic

# For iOS, you might need to add permissions in the Info.plist file for camera, microphone, and photo library usage.
# For Android, you might need to add permissions in the AndroidManifest.xml for storage and camera.
